### PR TITLE
[WIP] cleanup csv files

### PR DESCRIPTION
**Pull request by h3llrais3r**
WIP: do not yet merge, since I may add some more cleanup

- Cleanup quotes
- Replace `****` by `**`
- Replace `**` by `&#xA;`

### CODE REVIEW

**Comment by h3llrais3r** [comment]
In a lot of csv files, there are ** or **** symbols in the text.
** means new line 
(f.e. https://github.com/Wintermute0110/Game-database-info/blob/master/Nintendo%20Entertainment%20System.csv#L8 used for numbering)
**** means double new line = blank line 
(f.e. https://github.com/Wintermute0110/Game-database-info/blob/master/Nintendo%20Entertainment%20System.csv#L1 used for blank line between text blocks)

I'm just wondering: do we keep that also? I see that in most scraped results, no new lines and blank lines are used. If we decide to keep this, we need to specify a new line as [CR] according to the kodi docs to get a new line visible in the gui labels. Any thoughts on this?

**Comment by Wintermute0110** [comment]
Yes, ** means \n (new line). I'm not sure... maybe you can encode `**` into `\n` characters. I have to do some tests about how Kodi will behave. Another solution is to encode `**` as the XML LF (line feed) character `&#xA;`.

**Comment by h3llrais3r** [comment]
I'll try it... But `\n` is not working... I tried that yesterday.
When used for importing a game in kodi, the `\n` is not translated in CR/LF.
Will try it with `&#xA;` this evening.
But I'm still doubting if we should add blank lines (so replacing the `*****` by `**` would be better imho)

**Comment by Wintermute0110** [comment]
> But I'm still doubting if we should add blank lines (so replacing the ***** by ** would be better imho)

Agree.

**Comment by h3llrais3r** [comment]
I've just did a test and `&#xA;` works fine. So I'm going to replace all `**` by it.
All blank lines `****` will also be replaced by `&#xA;`.

**Comment by h3llrais3r** [comment]
Should I replace `**` by `&#xA;` in the csv files? Or do we do that during the conversion from csv to xml?

**Comment by Wintermute0110** [comment]
I think is better to fix the CSV. The cleaner the CSV files are, the simple the CSV to XML converter will be.

**Comment by h3llrais3r** [comment]
Anything else we can cleanup?

**Comment by Wintermute0110** [comment]
Thanks a lot h3llrais3r. Probably there are still a ton of thing to fix... but it is difficult sometimes to spot errors.

**Comment by h3llrais3r** [comment]
Indeed, you only notice it when you import a certain game for yourself. 😉

**Pull request merged**
