### PR TITLE
Replace some special characters by their ascii equivalent character

### PR DESCRIPTION
**Pull request by h3llrais3r**

### CODE REVIEW

**Comment by Wintermute0110** [comment]
**Thanks a lot** for this contribution. As I said, as soon as the CSV to XML converter is working OK for all platforms and the format of the "intermediate" XML is fixed we will abandon the CSV files. Fixing as many CSV files as possible before the conversion will save a lot of later headache, though.

**Comment by h3llrais3r** [comment]
Is there already an option to merge scraped info (from f.e. TheGamesDB) into the current xml files?
Perhaps that should be a good idea. If that's possible, someone could scrape the metadata from a complete set and merge it into the Games Database Info xml files.
Do you know where the original data was coming from? Because it's not clear in the original repo where the data is coming from.

**Comment by Wintermute0110** [comment]
> Is there already an option to merge scraped info (from f.e. TheGamesDB) into the current xml files?

Not at the moment. However, the AEL scraping engine can be used as an external module if you want to play with it.

> Perhaps that should be a good idea. If that's possible, someone could scrape the metadata from a complete set and merge it into the Games Database Info xml files.

I think the information in the CSV files are reasonably accurate. I estimate that no matter how good your scraper is, there is always going to be a 10% uncertainty. My original idea is to start with the XML files using the CSV files as they are, maybe doing small fixes during the CSV to XML conversion. Then, edit the XML by hand and combine with the No-Intro/Redump DATs.

> Do you know where the original data was coming from? Because it's not clear in the original repo where the data is coming from.

No. I never asked Billyc666 where he got the data from.

Later if I have time I will commit the changes so you can have a look. I'm sorry these weeks I'm really busy with real life to spend time on this.

**Comment by h3llrais3r** [comment]
Thanks for the info. 
No need to hurry, real life is more important than this. 😉

**Pull request merged**
